# Generated by Django 3.1.5 on 2021-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210228_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='user_posts', to='network.Post'),
        ),
    ]
